# Generated by Django 3.0.6 on 2020-05-08 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car0', models.FloatField(default=0, verbose_name='asymmetryByBestFitEllipse')),
                ('car1', models.FloatField(default=0, verbose_name='asymmetryByDistanceByCircle')),
                ('car2', models.FloatField(default=0, verbose_name='asymmetryIndex')),
                ('car3', models.FloatField(default=0, verbose_name='asymmetryBySubRegion')),
                ('car4', models.FloatField(default=0, verbose_name='asymmetryBySubRegionCentered')),
                ('car5', models.FloatField(default=0, verbose_name='asymmetryBySubRegionCentered2')),
                ('car6', models.FloatField(default=0, verbose_name='borderRoundness')),
                ('car7', models.FloatField(default=0, verbose_name='borderLength')),
                ('car8', models.FloatField(default=0, verbose_name='borderRegularityIndex')),
                ('car9', models.FloatField(default=0, verbose_name='borderRegularityIndexRatio')),
                ('car10', models.FloatField(default=0, verbose_name='borderCompactIndex')),
                ('car11', models.FloatField(default=0, verbose_name='borderHeywoodCircularityIndex')),
                ('car12', models.FloatField(default=0, verbose_name='borderHarrisCorner')),
                ('car13', models.FloatField(default=0, verbose_name='borderFractalDimension')),
                ('car14', models.FloatField(default=0, verbose_name='colorHSVIntervals')),
                ('car15', models.FloatField(default=0, verbose_name='colorYUVIntervals')),
                ('car16', models.FloatField(default=0, verbose_name='colorYCbCrIntervals')),
                ('car17', models.FloatField(default=0, verbose_name='colorSDG')),
                ('car18', models.FloatField(default=0, verbose_name='colorKurtosis')),
                ('car19', models.FloatField(default=0, verbose_name='diameterMinEnclosingCircle')),
                ('car20', models.FloatField(default=0, verbose_name='diameterOpenCircle')),
                ('car21', models.FloatField(default=0, verbose_name='diameterLengtheningIndex')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='computing date')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
            },
        ),
    ]
