# Generated by Django 2.1.15 on 2020-05-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='avatars/av.png', null=True, upload_to='avatars'),
        ),
    ]
