# Generated by Django 3.0.6 on 2020-05-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0004_auto_20200508_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
