# Generated by Django 3.0.4 on 2020-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0007_auto_20200506_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
