# Generated by Django 3.0.4 on 2020-05-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0007_auto_20200510_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristic',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melanomaApp.Image'),
        ),
    ]
