# Generated by Django 3.0.4 on 2020-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0008_auto_20200506_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='upload date'),
        ),
    ]
