# Generated by Django 3.0.4 on 2020-05-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0009_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melanomaApp.Image'),
        ),
    ]
