# Generated by Django 3.0.4 on 2020-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0009_auto_20200506_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asymmetryByBestFitEllipse', models.FloatField(default=0, verbose_name='asymmetryByBestFitEllipse')),
                ('asymmetryByDistanceByCircle', models.FloatField(default=0, verbose_name='asymmetryByDistanceByCircle')),
                ('asymmetryIndex', models.FloatField(default=0, verbose_name='asymmetryIndex')),
                ('asymmetryBySubRegion', models.FloatField(default=0, verbose_name='asymmetryBySubRegion')),
                ('asymmetryBySubRegionCentered', models.FloatField(default=0, verbose_name='asymmetryBySubRegionCentered')),
                ('asymmetryBySubRegionCentered2', models.FloatField(default=0, verbose_name='asymmetryBySubRegionCentered2')),
                ('borderRoundness', models.FloatField(default=0, verbose_name='borderRoundness')),
                ('borderLength', models.FloatField(default=0, verbose_name='borderLength')),
                ('borderRegularityIndex', models.FloatField(default=0, verbose_name='borderRegularityIndex')),
                ('borderRegularityIndexRatio', models.FloatField(default=0, verbose_name='borderRegularityIndexRatio')),
                ('borderCompactIndex', models.FloatField(default=0, verbose_name='borderCompactIndex')),
                ('borderHeywoodCircularityIndex', models.FloatField(default=0, verbose_name='borderHeywoodCircularityIndex')),
                ('borderHarrisCorner', models.FloatField(default=0, verbose_name='borderHarrisCorner')),
                ('borderFractalDimension', models.FloatField(default=0, verbose_name='borderFractalDimension')),
                ('colorHSVIntervals', models.FloatField(default=0, verbose_name='colorHSVIntervals')),
                ('colorYUVIntervals', models.FloatField(default=0, verbose_name='colorYUVIntervals')),
                ('colorYCbCrIntervals', models.FloatField(default=0, verbose_name='colorYCbCrIntervals')),
                ('colorSDG', models.FloatField(default=0, verbose_name='colorSDG')),
                ('colorKurtosis', models.FloatField(default=0, verbose_name='colorKurtosis')),
                ('diameterMinEnclosingCircle', models.FloatField(default=0, verbose_name='diameterMinEnclosingCircle')),
                ('diameterOpenCircle', models.FloatField(default=0, verbose_name='diameterOpenCircle')),
                ('diameterLengtheningIndex', models.FloatField(default=0, verbose_name='diameterLengtheningIndex')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='computing date')),
            ],
        ),
    ]
