# Generated by Django 3.0.4 on 2020-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0010_auto_20200510_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='extract',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
