# Generated by Django 3.0.4 on 2020-05-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0010_caracteristics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristics',
            old_name='asymmetryByBestFitEllipse',
            new_name='car0',
        ),
        migrations.RenameField(
            model_name='caracteristics',
            old_name='asymmetryByDistanceByCircle',
            new_name='car1',
        ),
        migrations.RenameField(
            model_name='caracteristics',
            old_name='borderCompactIndex',
            new_name='car10',
        ),
        migrations.RenameField(
            model_name='caracteristics',
            old_name='borderHeywoodCircularityIndex',
            new_name='car11',
        ),
        migrations.RenameField(
            model_name='caracteristics',
            old_name='borderHarrisCorner',
            new_name='car12',
        ),
        migrations.RenameField(
            model_name='caracteristics',
            old_name='borderFractalDimension',
            new_name='car13',
        ),
        migrations.RenameField(
            model_name='caracteristics',
            old_name='colorHSVIntervals',
            new_name='car14',
        ),
        migrations.RenameField(
            model_name='caracteristics',
            old_name='colorYCbCrIntervals',
            new_name='car16',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='asymmetryBySubRegion',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='asymmetryBySubRegionCentered',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='asymmetryBySubRegionCentered2',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='asymmetryIndex',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='borderLength',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='borderRegularityIndex',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='borderRegularityIndexRatio',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='borderRoundness',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='colorKurtosis',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='colorSDG',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='colorYUVIntervals',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='diameterLengtheningIndex',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='diameterMinEnclosingCircle',
        ),
        migrations.RemoveField(
            model_name='caracteristics',
            name='diameterOpenCircle',
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car15',
            field=models.FloatField(default=0, verbose_name='colorYUVIntervals'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car17',
            field=models.FloatField(default=0, verbose_name='colorSDG'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car18',
            field=models.FloatField(default=0, verbose_name='colorKurtosis'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car19',
            field=models.FloatField(default=0, verbose_name='diameterMinEnclosingCircle'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car2',
            field=models.FloatField(default=0, verbose_name='asymmetryIndex'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car20',
            field=models.FloatField(default=0, verbose_name='diameterOpenCircle'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car21',
            field=models.FloatField(default=0, verbose_name='diameterLengtheningIndex'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car3',
            field=models.FloatField(default=0, verbose_name='asymmetryBySubRegion'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car4',
            field=models.FloatField(default=0, verbose_name='asymmetryBySubRegionCentered'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car5',
            field=models.FloatField(default=0, verbose_name='asymmetryBySubRegionCentered2'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car6',
            field=models.FloatField(default=0, verbose_name='borderRoundness'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car7',
            field=models.FloatField(default=0, verbose_name='borderLength'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car8',
            field=models.FloatField(default=0, verbose_name='borderRegularityIndex'),
        ),
        migrations.AddField(
            model_name='caracteristics',
            name='car9',
            field=models.FloatField(default=0, verbose_name='borderRegularityIndexRatio'),
        ),
    ]
