# Generated by Django 3.0.4 on 2020-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0011_auto_20200510_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='contour',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
