# Generated by Django 3.0.4 on 2020-05-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0011_auto_20200506_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracteristics',
            new_name='Caracteristic',
        ),
    ]
