# Generated by Django 2.1.15 on 2020-05-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0011_auto_20200510_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(default='male', max_length=30),
        ),
    ]
