# Generated by Django 3.0.4 on 2020-05-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0012_details_contour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='contour',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='details',
            name='extract',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
