# Generated by Django 3.0.4 on 2020-05-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0013_auto_20200507_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor'},
        ),
    ]
