# Generated by Django 3.0.4 on 2020-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0014_auto_20200507_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imgName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
