# Generated by Django 3.0.4 on 2020-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0014_auto_20200512_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='contour',
        ),
        migrations.AlterField(
            model_name='details',
            name='extract',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
