# Generated by Django 3.0.4 on 2020-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0016_auto_20200512_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='circle',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
