# Generated by Django 3.0.4 on 2020-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0017_details_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='preprocess',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
