# Generated by Django 2.1.15 on 2020-05-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0020_details_rect'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='segmentation',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
