# Generated by Django 2.1.15 on 2020-05-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0021_details_segmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='posttraitement',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
