# Generated by Django 2.1.15 on 2020-05-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0026_note_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Patient',
        ),
    ]
