# Generated by Django 2.1.15 on 2020-05-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0027_remove_note_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melanomaApp.Image'),
        ),
    ]
