# Generated by Django 3.0.4 on 2020-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0030_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='border',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
