# Generated by Django 3.0.4 on 2020-05-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0031_details_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='borderlength',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
