# Generated by Django 3.0.4 on 2020-05-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0032_details_borderlength'),
        ('melanomaApp', '0032_image_result'),
    ]

    operations = [
    ]
