# Generated by Django 3.0.4 on 2020-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0033_merge_20200516_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='kmeans',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
