# Generated by Django 2.1.15 on 2020-05-16 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0033_merge_20200516_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
    ]
