# Generated by Django 3.0.4 on 2020-05-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0035_details_kmeans2'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='hsv',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
