# Generated by Django 3.0.4 on 2020-05-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melanomaApp', '0037_details_yuv'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ycbcr',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
